MANUAL = {
    "1F924": "slobbering, hungry for, desire, want, craving, lust, tempting, delicious looking",
    "1F920": "yeehaw, western, howdy, country, rodeo, confident, swagger, ranch",
    "1F921": "circus, creepy, scary, foolish, joke, ridiculous, not serious, embarrassing",
    "1F9E1": "143, warmth, autumn, friendship, affection, care, fondness",
    "1F90E": "143, warmth, earthy, affection, care, fondness",
    "1F90D": "143, pure, innocent, affection, care, fondness, clean",
    "1F573": "empty, void, gap, pit, nothing, missing, cavity, sink",
    "1F595": "rude, insult, offensive, anger, disrespect, screw you, vulgar",
    "270D": "writing, note, signature, author, compose, pen, journal, record",
    "1F91A": "stop, halt, wait, high five, pause, hold on, enough",
    "1F930": "expecting, baby, maternity, belly, birth, mother, soon",
    "1F9D1-200D-1FA70": "dance, graceful, performance, elegant, poise, theatre, discipline",
    "1F574": "mysterious, slick, business, suave, suspicious, agent, spy, cool",
    "1F98D": "strong, powerful, jungle, ape, primate, beast, muscle",
    "1F984": "magical, fantasy, rare, special, mythical, whimsical, dreamy",
    "1F418": "huge, massive, memory, never forgets, gentle giant, heavy, big",
    "1F400": "traitor, snitch, backstabber, betrayal, sneaky, disloyal",
    "1F42D": "tiny, small, timid, squeak, shy, little, cute",
    "1F578": "abandoned, neglected, dusty, forgotten, trap, old, unused, creepy",
    "1F940": "dying, fading, lost love, heartbreak, neglect, over, ending, sad",
    "1F341": "autumn, fall, canada, season, changing, cozy, leaves",
    "1F4AE": "pure, approval, well done, good job, pretty, delicate",
    "1F351": "butt, booty, flirty, suggestive, cheeky, sweet, juicy, summer",
    "1F336": "spicy, hot, fire, burning, attractive, intense, heat",
    "1F9C4": "pungent, vampire, cooking, strong smell, flavour, italian",
    "1F9C5": "layers, tears, crying, chopping, pungent, complexity",
    "1F9C0": "cheesy, smile for camera, dairy, say cheese, corny, snack",
    "1F356": "carnivore, protein, caveman, hearty, barbecue, feast, hungry",
    "1F32E": "mexican, street food, tuesday, casual, spicy, craving",
    "1F957": "healthy, diet, light, fresh, greens, clean eating, rabbit food",
    "1F9C8": "rich, smooth, fat, spread, creamy, baking, indulgent",
    "1F371": "lunch, packed, japanese, organised, neat, compartments, meal prep",
    "1F363": "japanese, raw, fancy, date night, fresh, expensive, treat",
    "1F960": "future, prophecy, luck, wisdom, chinese, message, destiny",
    "1F384": "christmas, holidays, festive, winter, december, family, gifts",
    "1F380": "gift, present, pretty, decoration, cute, wrapped, bow",
    "1F397": "awareness, cause, support, solidarity, remember, charity",
    "1F94A": "fight, punch, competition, tough, defend, spar, knockout",
    "1F945": "score, target, aim, achieve, football, soccer, objective",
    "26F8": "winter, cold, rink, glide, graceful, sport, slippery",
}